# Generated by Django 5.2 on 2025-05-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='address',
        ),
    ]
