# Generated by Django 5.2 on 2025-05-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_receiver_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='has_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
