# Generated by Django 5.2 on 2025-05-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_donor_bloodgroup_donor_dob_donor_has_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(null=True),
        ),
    ]
