# Generated by Django 5.2 on 2025-05-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='scheduled_time',
            field=models.TimeField(null=True),
        ),
    ]
