# Generated by Django 5.2 on 2025-05-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_donation_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
