# Generated by Django 5.2 on 2025-05-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_bloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='bloodgroup',
            field=models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
