# Generated by Django 5.2 on 2025-05-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_receiver_bloodgroup_receiver_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='requested_at',
            field=models.DateTimeField(),
        ),
    ]
