# Generated by Django 5.2 on 2025-05-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_bloodrequest_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='required_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='requested_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
