# Generated by Django 5.2 on 2025-05-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_bloodrequest_required_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='contact',
        ),
    ]
